In [4]:
import pandas as pd

In [5]:
store = pd.HDFStore("example.hd5")

In [6]:
store.CalibratedPulses[store.CalibratedPulses.Event==2]

,Run,Event,exists,TriggerCounter,string,om,vector_index,time,width,charge,id,isTriggered
0,45978,2,1,57188,1,2,0,4092.700717,NaN,0.819998,44,0
1,45978,2,1,57188,1,4,0,3720.667352,NaN,0.561300,129,0
2,45978,2,1,57188,1,8,0,6121.324395,NaN,0.423320,137,0
3,45978,2,1,57188,1,12,0,5362.249247,NaN,0.862963,87,0
4,45978,2,1,57188,1,16,0,5883.653970,NaN,1.061923,23,0
5,45978,2,1,57188,1,18,0,6930.661182,NaN,1.000524,32,0
6,45978,2,1,57188,1,22,0,6350.888814,NaN,0.563675,36,0
7,45978,2,1,57188,1,22,1,3601.034390,NaN,1.333916,38,0
8,45978,2,1,57188,1,27,0,4062.590055,NaN,4.466157,18,0
9,45978,2,1,57188,1,27,1,5888.824709,NaN,1.138825,19,0
10,45978,2,1,57188,1,27,2,5455.589457,NaN,1.405773,21,0
11,45978,2,1,57188,1,37,0,6709.808404,NaN,1.510831,99,0
12,45978,2,1,57188,1,38,0,5364.887937,NaN,0.719694,103,0
13,45978,2,1,57188,1,43,0,5356.120161,NaN,0.799824,52,0
14,45978,2,1,57188,1,45,0,6787.553895,NaN,1.957944,57,0
15,45978,2,1,57188,1,49,0,4017.880130,NaN,0.216622,43,0
16,45978,2,1,57188,1,51,0,3338.428269,NaN,1.324314,47,0
17,45978,2,1,57188,1,51,1,3293.485042,NaN,0.491035,49,0
18,45978,2,1,57188,1,56,0,5427.342486,NaN,0.704921,92,0
19,45978,2,1,57188,1,56,1,4687.966654,NaN,0.431727,93,0
20,45978,2,1,57188,1,72,0,4506.100426,NaN,1.465480,95,0
21,45978,2,1,57188,1,72,1,5471.645232,NaN,0.808342,96,0
22,45978,2,1,57188,2,5,0,4746.251954,NaN,0.908766,26,0
23,45978,2,1,57188,2,12,0,5435.916521,NaN,0.522364,11,0
24,45978,2,1,57188,2,23,0,7088.790150,NaN,0.995929,111,0
25,45978,2,1,57188,2,29,0,4349.021338,NaN,1.286056,24,0
26,45978,2,1,57188,2,31,0,3719.951229,NaN,1.333059,109,0
27,45978,2,1,57188,2,32,0,6596.952465,NaN,1.716753,116,0
28,45978,2,1,57188,2,48,0,6418.124205,NaN,1.172891,124,0
29,45978,2,1,57188,2,49,0,4881.411920,NaN,1.399015,90,0
...,...,...,...,...,...,...,...,...,...,...,...,...
556,45978,2,1,57192,10,72,0,3724.712423,NaN,1.364341,95,0
557,45978,2,1,57192,10,75,0,6019.573451,NaN,1.140176,10,0
558,45978,2,1,57192,11,19,0,4295.049574,NaN,0.466871,142,0
559,45978,2,1,57192,11,29,0,5377.279026,NaN,1.135662,6,0
560,45978,2,1,57192,11,37,0,6558.308526,NaN,1.525232,66,0
561,45978,2,1,57192,11,40,0,6008.048736,NaN,0.331947,46,0
562,45978,2,1,57192,11,40,1,4770.080887,NaN,1.614006,48,0
563,45978,2,1,57192,11,41,0,5299.254523,NaN,0.979528,50,0
564,45978,2,1,57192,11,50,0,6636.216506,NaN,1.018077,87,0
565,45978,2,1,57192,11,51,0,4696.929434,NaN,1.592751,88,0
566,45978,2,1,57192,11,52,0,3494.630965,NaN,1.420392,97,0
567,45978,2,1,57192,11,53,0,4022.118130,NaN,3.503563,99,0
568,45978,2,1,57192,11,53,1,5980.967789,NaN,0.861323,100,0
569,45978,2,1,57192,11,54,0,5067.833105,NaN,1.114462,103,0
570,45978,2,1,57192,11,65,0,3524.701758,NaN,0.761944,157,0
571,45978,2,1,57192,11,73,0,5538.403486,NaN,1.011277,146,0
572,45978,2,1,57192,11,74,0,5974.464025,NaN,1.033400,147,0
573,45978,2,1,57192,12,1,0,6861.397647,NaN,0.750251,137,0
574,45978,2,1,57192,12,4,0,5113.981138,NaN,2.185622,13,0
575,45978,2,1,57192,12,4,1,7177.729417,NaN,2.901098,14,0
576,45978,2,1,57192,12,4,2,5487.483446,NaN,0.928578,17,0
577,45978,2,1,57192,12,5,0,3905.953008,NaN,1.253825,18,0
578,45978,2,1,57192,12,20,0,4165.451891,NaN,0.717164,98,0
579,45978,2,1,57192,12,22,0,4162.596810,NaN,0.657860,153,0
580,45978,2,1,57192,12,23,0,6405.585797,NaN,0.857765,155,0
581,45978,2,1,57192,12,34,0,4735.479278,NaN,1.317987,134,0
582,45978,2,1,57192,12,44,0,4895.268656,NaN,1.159165,154,0
583,45978,2,1,57192,12,46,0,4078.763691,NaN,1.371296,135,0
584,45978,2,1,57192,12,49,0,6438.230340,NaN,1.352533,67,0
585,45978,2,1,57192,12,50,0,3207.006567,NaN,1.600555,69,0